/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package garima.hospital.management.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import garima.hospital.management.Logic.HospitalManagementLogic;
import garima.hospital.management.struts.form.HospitalManagementForm;

public class HospitalManagementAction extends DispatchAction {

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");

		return mapping.findForward("login");
	}

	public ActionForward loginpage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		hospitalManagementForm.setErrorMessage("");
		//------------- Check the username and password from the database --------------
		
		HospitalManagementLogic hospitalManagementLogic=new HospitalManagementLogic();
		hospitalManagementForm.setErrorMessage("");
		if(hospitalManagementLogic.verifyUser(hospitalManagementForm.getUsername(), hospitalManagementForm.getPassword())==2)
			return mapping.findForward("employee");
		else if(hospitalManagementLogic.verifyUser(hospitalManagementForm.getUsername(), hospitalManagementForm.getPassword())==0)
			return mapping.findForward("patientdetails");
		hospitalManagementForm.setUsername("");
		hospitalManagementForm.setPassword("");
		hospitalManagementForm.setErrorMessage("Invalid User");
		return mapping.findForward("login");
		
/*		
		
		if(hospitalManagementForm.getUsername().equals("hospitalManagement")&&hospitalManagementForm.getPassword().equals("hospitalManagement"))
			return mapping.findForward("employee");
		hospitalManagementForm.setUsername("");
		hospitalManagementForm.setPassword("");
		hospitalManagementForm.setErrorMessage("Invalid User");
		return mapping.findForward("login");*/
	}
	
	public ActionForward admin1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		
		return mapping.findForward("adminlogin");
	}
	
	public ActionForward admin11(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		HospitalManagementLogic hospitalManagementLogic=new HospitalManagementLogic();
		hospitalManagementForm.setErrorMessage("");
		if(hospitalManagementLogic.verifyUser(hospitalManagementForm.getUsername(), hospitalManagementForm.getPassword())==1)
			return mapping.findForward("adminmainpage");
		hospitalManagementForm.setUsername("");
		hospitalManagementForm.setPassword("");
		hospitalManagementForm.setErrorMessage("Invalid User");
		return mapping.findForward("adminlogin");
	}


	public ActionForward newuser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		HospitalManagementLogic hospitalManagementLogic=new HospitalManagementLogic();
		hospitalManagementForm.setErrorMessage("");
		if(hospitalManagementLogic.addNewEmployee(hospitalManagementForm.getUserid(), hospitalManagementForm.getPassword(), hospitalManagementForm.getFirstname(), hospitalManagementForm.getLastname(), hospitalManagementForm.getPermanentaddress(), hospitalManagementForm.getPhonenumber(), Integer.valueOf(hospitalManagementForm.getSex()), hospitalManagementForm.getNationality(), hospitalManagementForm.getTextverification(), 0, hospitalManagementForm.getConsultinghours(), hospitalManagementForm.getQualification(), hospitalManagementForm.getSpecialist())==1)
			hospitalManagementForm.setErrorMessage("User Name Created Successfully");
		else
			hospitalManagementForm.setErrorMessage("User Name Already Exixts (Create with New User Name)");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("login");
		//--------------- Create a new user in the database --------------
	}
	
	public ActionForward employees(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Coding for the login users --------------
		return mapping.findForward("login");
	}
	
	public ActionForward frontofficemanager(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("frontofficemanager");
	}

	public ActionForward doctordetails(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("doctordetails");
	}
	
	public ActionForward doctordetails1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("doctordetails");
	}

	public ActionForward healthawareness(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("healthawareness");
	}
	
	public ActionForward healthawareness1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("healthawareness");
	}
	
	public ActionForward systemreports(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("systemreport");
	}
	
	
	
	
	public ActionForward appointmentscheduling(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("appointmentscheduling");
	}
	
	public ActionForward appointmentscheduling1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		HospitalManagementLogic hospitalManagementLogic=new HospitalManagementLogic();
		if(hospitalManagementLogic.appointmentScheduling(hospitalManagementForm.getPatientname(), Integer.valueOf(hospitalManagementForm.getPatientage()), Integer.valueOf(hospitalManagementForm.getPatientsex()), hospitalManagementForm.getPatienthealthproblem(), hospitalManagementForm.getPatientdate(), request.getParameter("patienttime"))==1)
			hospitalManagementForm.setErrorMessage("Appointment OK");
		else
			hospitalManagementForm.setErrorMessage("No Appointment");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("appointmentscheduling");
	}

	public ActionForward appointmentrescheduling(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("appointmentrescheduling");
	}

	public ActionForward patientinformation(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("login");
	}
	
	public ActionForward roomassignment(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("login");
	}

	
	
	
	
	public ActionForward appointmentreports(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("appointmentreports");
	}
	
	public ActionForward appointmentreports1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("appointmentreports");
	}
	
	public ActionForward loginerrors(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("login");
	}
	
	public ActionForward billgeneration(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("login");
	}
	
	public ActionForward addnewequipment(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("addnewequipment");
	}
	
	public ActionForward addnewequipment1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		HospitalManagementLogic hospitalManagementLogic=new HospitalManagementLogic();
		if(hospitalManagementLogic.addNewEquipment(hospitalManagementForm.getEquipmentname(), Float.valueOf(hospitalManagementForm.getEquipmentfees()))==1)
			hospitalManagementForm.setErrorMessage("Equipment Added Successfully");
		else
			hospitalManagementForm.setErrorMessage("Equipment Not Added");
		
		//------------- Check the username and password from the database --------------
		return mapping.findForward("addnewequipment");
	}

	public ActionForward addemployee(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		System.out.println("Checking...");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("newuseradmin");
	}

	public ActionForward addemployee1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HospitalManagementForm hospitalManagementForm = (HospitalManagementForm) form;// TODO Auto-generated method stub
		HospitalManagementLogic hospitalManagementLogic=new HospitalManagementLogic();
		hospitalManagementForm.setErrorMessage("");
		if(hospitalManagementLogic.addNewEmployee(hospitalManagementForm.getUserid(), hospitalManagementForm.getPassword(), hospitalManagementForm.getFirstname(), hospitalManagementForm.getLastname(), hospitalManagementForm.getPermanentaddress(), hospitalManagementForm.getPhonenumber(), Integer.valueOf(hospitalManagementForm.getSex()), hospitalManagementForm.getNationality(), hospitalManagementForm.getTextverification(), Integer.valueOf(hospitalManagementForm.getType()), hospitalManagementForm.getConsultinghours(), hospitalManagementForm.getQualification(), hospitalManagementForm.getSpecialist())==1)
			hospitalManagementForm.setErrorMessage("User Name Created Successfully");
		else
			hospitalManagementForm.setErrorMessage("User Name Already Exixts (Create with New User Name)");
		//------------- Check the username and password from the database --------------
		return mapping.findForward("newuseradmin");
	}
	


	
	
	

	

}